"""
Utility functions for Master Productivity Prompt Studio
Created by: Dr Alok Tiwari
"""

import html
import json
import os
import re
import tempfile
import uuid
from datetime import datetime
from io import BytesIO
from pathlib import Path

import streamlit as st

# ─── Paths ────────────────────────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
SAVED_PROMPTS_FILE = os.path.join(DATA_DIR, "saved_prompts.json")
SAMPLE_INPUTS_FILE = os.path.join(DATA_DIR, "sample_inputs.json")
TEMPLATES_FILE = os.path.join(DATA_DIR, "prompt_templates.json")


def ensure_data_files() -> None:
    """Create the local data folder and writable library file if they are missing."""
    os.makedirs(DATA_DIR, exist_ok=True)
    if not os.path.exists(SAVED_PROMPTS_FILE):
        save_json(SAVED_PROMPTS_FILE, [])


def escape_html(text: str) -> str:
    """Escape text before injecting it into custom HTML blocks."""
    return html.escape(text or "", quote=True)


def safe_filename(name: str, fallback: str = "download") -> str:
    """Return a filesystem-safe filename while preserving readability."""
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "_", (name or fallback).strip()).strip("._")
    return cleaned[:80] or fallback


def _uploaded_bytes(uploaded) -> bytes:
    """Read bytes from a Streamlit UploadedFile without depending on pointer state."""
    if uploaded is None:
        return b""
    if hasattr(uploaded, "getvalue"):
        return uploaded.getvalue()
    return uploaded.read()


def extract_text_from_upload(uploaded) -> str:
    """Extract text from TXT, PDF, or DOCX uploads with graceful fallbacks."""
    if uploaded is None:
        return ""

    filename = getattr(uploaded, "name", "uploaded_file")
    ext = filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    raw = _uploaded_bytes(uploaded)

    if not raw:
        return ""

    if ext == "txt":
        return raw.decode("utf-8", errors="replace").strip()

    if ext == "pdf":
        try:
            import pypdf
            reader = pypdf.PdfReader(BytesIO(raw))
            return "\n\n".join(page.extract_text() or "" for page in reader.pages).strip()
        except ImportError:
            try:
                import pdfplumber
                with pdfplumber.open(BytesIO(raw)) as pdf:
                    return "\n\n".join(page.extract_text() or "" for page in pdf.pages).strip()
            except ImportError as exc:
                raise RuntimeError("PDF support requires `pypdf` or `pdfplumber`. Run `pip install pypdf`.") from exc

    if ext == "docx":
        try:
            import docx as _docx
            doc = _docx.Document(BytesIO(raw))
            return "\n".join(p.text for p in doc.paragraphs if p.text.strip()).strip()
        except ImportError:
            try:
                import docx2txt
                with tempfile.NamedTemporaryFile(suffix=".docx", delete=False) as tmp:
                    tmp.write(raw)
                    tmp_path = tmp.name
                try:
                    return (docx2txt.process(tmp_path) or "").strip()
                finally:
                    try:
                        os.remove(tmp_path)
                    except OSError:
                        pass
            except ImportError as exc:
                raise RuntimeError("DOCX support requires `python-docx` or `docx2txt`. Run `pip install python-docx`.") from exc

    raise RuntimeError(f"Unsupported file type: .{ext or 'unknown'}. Please upload TXT, PDF, or DOCX.")


def build_docx_bytes(title: str, body: str) -> bytes:
    """Create a simple DOCX file in memory for generated prompts."""
    try:
        import docx
    except ImportError as exc:
        raise RuntimeError("DOCX export requires `python-docx`. Install it with `pip install python-docx`.") from exc

    document = docx.Document()
    document.add_heading(title or "Generated Master Prompt", level=1)
    document.add_paragraph("Generated by Master Productivity Prompt Studio — Dr Alok Tiwari")
    document.add_paragraph("")
    for block in (body or "").split("\n"):
        document.add_paragraph(block)
    buffer = BytesIO()
    document.save(buffer)
    return buffer.getvalue()


# ─── Load / Save helpers ──────────────────────────────────────────────────────
def load_json(filepath: str, default=None):
    if default is None:
        default = []
    try:
        if os.path.exists(filepath):
            with open(filepath, "r", encoding="utf-8") as f:
                return json.load(f)
    except json.JSONDecodeError:
        # Keep the app usable even if a local JSON file is damaged.
        backup = f"{filepath}.corrupt_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        try:
            os.replace(filepath, backup)
        except OSError:
            pass
    except Exception:
        pass
    return default


def save_json(filepath: str, data):
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def load_sample_inputs() -> dict:
    return load_json(SAMPLE_INPUTS_FILE, {})


def load_templates() -> dict:
    return load_json(TEMPLATES_FILE, {})


def load_saved_prompts() -> list:
    return load_json(SAVED_PROMPTS_FILE, [])


def save_prompts_to_disk(prompts: list):
    os.makedirs(DATA_DIR, exist_ok=True)
    save_json(SAVED_PROMPTS_FILE, prompts)


# ─── Prompt library helpers ───────────────────────────────────────────────────
def save_prompt_to_library(title: str, category: str, tags: list, prompt_text: str):
    """Append a new prompt entry to the library JSON."""
    prompts = load_saved_prompts()
    entry = {
        "id": str(uuid.uuid4()),
        "title": title,
        "category": category,
        "tags": tags,
        "prompt": prompt_text,
        "created_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat(),
    }
    prompts.append(entry)
    save_prompts_to_disk(prompts)
    return entry


def delete_prompt_from_library(prompt_id: str):
    prompts = load_saved_prompts()
    prompts = [p for p in prompts if p.get("id") != prompt_id]
    save_prompts_to_disk(prompts)


def update_prompt_in_library(prompt_id: str, updates: dict):
    prompts = load_saved_prompts()
    for p in prompts:
        if p.get("id") == prompt_id:
            p.update(updates)
            p["updated_at"] = datetime.now().isoformat()
    save_prompts_to_disk(prompts)


# ─── UI helpers ───────────────────────────────────────────────────────────────
def section_header(title: str, icon: str = ""):
    st.markdown(
        f"""
        <div class="section-header">
            <span class="section-icon">{icon}</span>
            <span class="section-title">{title}</span>
        </div>
        """,
        unsafe_allow_html=True,
    )


def info_card(text: str, color: str = "#FF6B35"):
    st.markdown(
        f"""<div style="background:linear-gradient(135deg,{color}18,{color}08);
        border-left:4px solid {color};border-radius:8px;padding:12px 16px;
        margin:8px 0;font-size:0.92rem;">{text}</div>""",
        unsafe_allow_html=True,
    )


def studio_tabs(key_prefix: str, has_preview: bool = False):
    """
    Render a clean, single-row tab selector for each studio module.

    The selector is backed by a native Streamlit radio widget for accessibility
    and responsiveness. Programmatic navigation, such as jumping to Final
    Prompt after generation, is handled through a separate pending-tab key.
    This avoids Streamlit's rule against modifying a widget-backed
    ``st.session_state`` key after that widget has already been instantiated
    during the current run.
    """
    tab_key = f"{key_prefix}_active_tab"
    requested_key = f"{key_prefix}_requested_tab"
    options = ["input", "output"]
    labels = {"input": "Inputs", "preview": "Preview", "output": "Final Prompt"}

    if has_preview:
        options = ["input", "preview", "output"]

    # Apply any tab switch requested during the previous run before the radio
    # widget is created. This is the safe way to move users to the output tab
    # after they click Generate Prompt inside the input tab.
    requested = st.session_state.pop(requested_key, None)
    if requested in options:
        st.session_state[tab_key] = requested

    if st.session_state.get(tab_key) not in options:
        st.session_state[tab_key] = "input"

    active = st.radio(
        label=f"studio tab navigation {key_prefix}",
        options=options,
        index=options.index(st.session_state[tab_key]),
        format_func=lambda value: labels[value],
        horizontal=True,
        label_visibility="collapsed",
        key=tab_key,
        help="Switch between the input workspace and the generated output.",
    )
    return active


def request_studio_tab(key_prefix: str, target_tab: str):
    """Request a tab switch for the next rerun without touching widget state."""
    st.session_state[f"{key_prefix}_requested_tab"] = target_tab
    st.rerun()


def go_to_output(key_prefix: str):
    """Switch the studio tab to Final Prompt and trigger a rerun safely."""
    request_studio_tab(key_prefix, "output")


def _copy_button_html(text: str, btn_key: str) -> str:
    """Return a self-contained HTML+JS clipboard copy button."""
    # JSON encodes the prompt for JavaScript; HTML escaping keeps the onclick attribute safe.
    safe = escape_html(json.dumps(text or ""))
    safe_key = safe_filename(btn_key, fallback="copy")
    return f"""
    <div style="margin:0;">
      <button id="cpbtn_{safe_key}"
        onclick='(function(){{
          var txt = {safe};
          function done(){{
            var b = document.getElementById("cpbtn_{safe_key}");
            var orig = b.innerHTML;
            b.innerHTML = "✅ Copied!";
            b.style.background = "#2E7D52";
            setTimeout(function(){{ b.innerHTML = orig; b.style.background = ""; }}, 2000);
          }}
          if(navigator.clipboard && navigator.clipboard.writeText){{
            navigator.clipboard.writeText(txt).then(done);
          }} else {{
            var ta = document.createElement("textarea");
            ta.value = txt;
            ta.style.position = "fixed";
            ta.style.opacity = "0";
            document.body.appendChild(ta);
            ta.select();
            document.execCommand("copy");
            document.body.removeChild(ta);
            done();
          }}
        }})();'
        style="
          width:100%;
          min-height:42px;
          padding:9px 14px;
          background:linear-gradient(135deg,#E8651A,#C4500F);
          color:#fff;
          border:none;
          border-radius:8px;
          font-size:0.88rem;
          font-weight:700;
          cursor:pointer;
          letter-spacing:0.02em;
          box-shadow:0 2px 6px rgba(196,80,15,0.3);
          transition:all 0.2s;
          white-space:normal;
        "
        onmouseover="this.style.transform='translateY(-1px)';this.style.boxShadow='0 5px 14px rgba(196,80,15,0.4)';"
        onmouseout="this.style.transform='';this.style.boxShadow='0 2px 6px rgba(196,80,15,0.3)';"
      >📋 Copy Prompt</button>
    </div>
    """


def prompt_output_section(prompt_text: str, key_prefix: str, category: str = "General"):
    """Render generated prompt with Preview, Copy, Download, Save and Clear controls."""
    import streamlit.components.v1 as components

    st.markdown("---")

    # ── Header row ────────────────────────────────────────────────────────────
    st.markdown(
        """<div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;">
            <span style="font-size:1.4rem;">📋</span>
            <span style="font-family:'Playfair Display',serif;font-size:1.3rem;
                  font-weight:700;color:#C4500F;">Generated Master Prompt</span>
        </div>""",
        unsafe_allow_html=True,
    )

    # ── Stat bar ──────────────────────────────────────────────────────────────
    word_count = len(prompt_text.split())
    char_count = len(prompt_text)
    line_count = prompt_text.count("\n") + 1
    st.markdown(
        f"""<div style="background:#FFF3E8;border:1px solid #EDE0D0;border-radius:8px;
            padding:8px 16px;margin-bottom:14px;display:flex;gap:28px;flex-wrap:wrap;">
            <span style="font-size:0.83rem;color:#5A5A6A;">
                📝 <b style="color:#C4500F;">{word_count:,}</b> words
            </span>
            <span style="font-size:0.83rem;color:#5A5A6A;">
                🔤 <b style="color:#C4500F;">{char_count:,}</b> characters
            </span>
            <span style="font-size:0.83rem;color:#5A5A6A;">
                📄 <b style="color:#C4500F;">{line_count}</b> lines
            </span>
            <span style="font-size:0.83rem;color:#5A5A6A;">
                🏷 Category: <b style="color:#C4500F;">{category}</b>
            </span>
        </div>""",
        unsafe_allow_html=True,
    )

    # ── Output tabs: Edit | Preview ───────────────────────────────────────────
    edit_tab, preview_tab = st.tabs(["✏️ Edit Prompt", "👁 Preview"])

    with edit_tab:
        edited = st.text_area(
            "Edit your prompt before copying, saving, or downloading:",
            value=prompt_text,
            height=400,
            key=f"{key_prefix}_edit",
            help="Make any adjustments here. All action buttons below use this edited version.",
        )

    with preview_tab:
        # Read whatever is in the edit box (may differ from original)
        current = st.session_state.get(f"{key_prefix}_edit", prompt_text)
        st.markdown(
            f"""<div style="background:#FAFAFA;border:1px solid #EDE0D0;border-radius:10px;
                padding:20px 24px;font-family:'Source Sans 3',sans-serif;
                font-size:0.93rem;line-height:1.7;color:#2C2C2C;
                white-space:pre-wrap;word-break:break-word;max-height:440px;overflow-y:auto;">
                {escape_html(current)}
            </div>""",
            unsafe_allow_html=True,
        )

    # Use the edited value going forward (default to original if widget not yet rendered)
    edited = st.session_state.get(f"{key_prefix}_edit", prompt_text)

    st.markdown("<div style='margin-top:14px;'></div>", unsafe_allow_html=True)

    # ── Action row ────────────────────────────────────────────────────────────
    # Row 1 : Copy | Download TXT | Download MD | Download DOCX
    col_copy, col_txt, col_md, col_docx = st.columns(4)

    with col_copy:
        components.html(
            _copy_button_html(edited, btn_key=key_prefix),
            height=46,
            scrolling=False,
        )

    with col_txt:
        st.download_button(
            "⬇ TXT",
            data=edited,
            file_name=f"prompt_{key_prefix}.txt",
            mime="text/plain",
            use_container_width=True,
            key=f"{key_prefix}_dl_txt",
        )

    with col_md:
        md_content = (
            f"# Master Prompt — {category}\n\n"
            f"```\n{edited}\n```\n\n"
            f"---\n*Generated by Master Productivity Prompt Studio — Dr Alok Tiwari*"
        )
        st.download_button(
            "⬇ MD",
            data=md_content,
            file_name=f"prompt_{key_prefix}.md",
            mime="text/markdown",
            use_container_width=True,
            key=f"{key_prefix}_dl_md",
        )

    with col_docx:
        try:
            docx_data = build_docx_bytes(f"Master Prompt — {category}", edited)
            st.download_button(
                "⬇ DOCX",
                data=docx_data,
                file_name=f"prompt_{key_prefix}.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True,
                key=f"{key_prefix}_dl_docx",
            )
        except Exception:
            st.button("DOCX unavailable", disabled=True, use_container_width=True, key=f"{key_prefix}_dl_docx_disabled")

    # Row 2 : Save to Library | Clear
    st.markdown("<div style='margin-top:8px;'></div>", unsafe_allow_html=True)
    col_save, col_clear = st.columns([3, 1])

    with col_save:
        if st.button("💾 Save to Library", key=f"{key_prefix}_save_btn", use_container_width=True):
            st.session_state[f"{key_prefix}_show_save"] = True

    with col_clear:
        if st.button("🗑 Clear", key=f"{key_prefix}_clear", use_container_width=True):
            # Reset the prompt key so the studio shows the empty state
            prompt_store_key = f"{key_prefix}_prompt"
            if prompt_store_key in st.session_state:
                st.session_state[prompt_store_key] = ""
            st.rerun()

    # ── Save form ─────────────────────────────────────────────────────────────
    if st.session_state.get(f"{key_prefix}_show_save"):
        st.markdown("<div style='margin-top:10px;'></div>", unsafe_allow_html=True)
        with st.expander("💾 Save Prompt to Library", expanded=True):
            sc1, sc2 = st.columns(2)
            with sc1:
                save_title = st.text_input(
                    "Prompt Title *",
                    value=f"{category} — {datetime.now().strftime('%d %b %Y %H:%M')}",
                    placeholder="e.g., My Research Gap Analysis Prompt",
                    key=f"{key_prefix}_stitle",
                )
            with sc2:
                save_tags_raw = st.text_input(
                    "Tags (comma-separated)",
                    placeholder="e.g., research, gap, synthesis",
                    key=f"{key_prefix}_stags",
                )
            btn_c1, btn_c2 = st.columns([2, 1])
            with btn_c1:
                if st.button("✅ Confirm Save", key=f"{key_prefix}_confirm_save", use_container_width=True):
                    if save_title.strip():
                        tags = [t.strip() for t in save_tags_raw.split(",") if t.strip()]
                        save_prompt_to_library(save_title.strip(), category, tags, edited)
                        st.success(f"✅ '{save_title}' saved to Prompt Library!")
                        st.session_state[f"{key_prefix}_show_save"] = False
                    else:
                        st.warning("Please enter a title before saving.")
            with btn_c2:
                if st.button("✖ Cancel", key=f"{key_prefix}_cancel_save", use_container_width=True):
                    st.session_state[f"{key_prefix}_show_save"] = False
                    st.rerun()

    return edited


def global_sidebar_fields(sample: dict, key_prefix: str = "") -> dict:
    """Render common global settings + persistent author name in sidebar."""
    st.sidebar.markdown("---")

    # ── Persistent author name (shared across all modules) ────────────────────
    st.sidebar.markdown("**👤 Your Name**")
    if "global_author" not in st.session_state:
        st.session_state["global_author"] = "Dr Alok Tiwari"

    author_col, edit_col = st.sidebar.columns([3, 1])
    with author_col:
        # Show current name as badge
        st.sidebar.markdown(
            f"""<div style="background:#2C1A08;border:1px solid #5A3A1A;border-radius:6px;
            padding:6px 10px;font-size:0.88rem;color:#F5E6D3;margin-bottom:4px;">
            {st.session_state['global_author']}</div>""",
            unsafe_allow_html=True,
        )

    # Toggle edit mode
    if "author_edit_mode" not in st.session_state:
        st.session_state["author_edit_mode"] = False

    if st.sidebar.button(
        "✏️ Edit Name" if not st.session_state["author_edit_mode"] else "✖ Cancel",
        key="toggle_author_edit",
        use_container_width=True,
    ):
        st.session_state["author_edit_mode"] = not st.session_state["author_edit_mode"]

    if st.session_state["author_edit_mode"]:
        new_name = st.sidebar.text_input(
            "Enter your name:",
            value=st.session_state["global_author"],
            key="author_name_input",
            placeholder="e.g., Dr Jane Smith",
        )
        if st.sidebar.button("✅ Save Name", key="save_author_name", use_container_width=True):
            if new_name.strip():
                st.session_state["global_author"] = new_name.strip()
                st.session_state["author_edit_mode"] = False
                st.rerun()
            else:
                st.sidebar.warning("Name cannot be empty.")

    author = st.session_state["global_author"]

    # ── Global prompt settings ────────────────────────────────────────────────
    st.sidebar.markdown("---")
    st.sidebar.markdown("**⚙️ Prompt Settings**")

    tone = st.sidebar.selectbox(
        "Tone",
        sample.get("tones", ["Academic", "Professional"]),
        key=f"{key_prefix}_tone",
    )
    output_format = st.sidebar.selectbox(
        "Output Format",
        sample.get("output_formats", ["Full master prompt"]),
        key=f"{key_prefix}_format",
    )
    length = st.sidebar.selectbox(
        "Length",
        sample.get("lengths", ["Detailed"]),
        key=f"{key_prefix}_length",
    )
    return {"tone": tone, "output_format": output_format, "length": length, "author": author}


# ─── File upload helper ───────────────────────────────────────────────────────
def file_upload_field(
    label: str,
    key: str,
    fallback_key: str,
    placeholder: str = "Or paste text directly here...",
    height: int = 180,
    accepted_types: list = None,
) -> str:
    """
    Render a file-upload widget (PDF / DOCX / TXT) with a textarea fallback.
    Returns the extracted / pasted text content as a string.

    Parameters
    ----------
    label         : Section label shown above the widget
    key           : Unique key for the file_uploader widget
    fallback_key  : Unique key for the textarea fallback
    placeholder   : Placeholder text for the textarea
    height        : Height of the textarea
    accepted_types: List of extensions e.g. ["pdf","docx","txt"]. Defaults to all three.
    """
    if accepted_types is None:
        accepted_types = ["pdf", "docx", "txt"]

    st.markdown(
        f"""<div style="background:#F9F1E8;border:1px dashed #D4A017;border-radius:8px;
        padding:12px 16px;margin-bottom:10px;">
        <div style="font-weight:700;color:#C4500F;font-size:0.93rem;margin-bottom:6px;">
            📎 {label}
        </div>
        <div style="font-size:0.8rem;color:#5A5A6A;">
            Upload a file <b>or</b> paste text below. Supported: {', '.join(f'.{e}' for e in accepted_types)}.
        </div>
        </div>""",
        unsafe_allow_html=True,
    )

    uploaded = st.file_uploader(
        f"Upload {label}",
        type=accepted_types,
        key=key,
        label_visibility="collapsed",
    )

    extracted = ""
    if uploaded is not None:
        try:
            extracted = extract_text_from_upload(uploaded)
            if extracted:
                st.success(
                    f"✅ Extracted **{len(extracted.split()):,} words** "
                    f"from `{uploaded.name}` — review below."
                )
            else:
                st.warning("The uploaded file was readable but no text could be extracted. Please paste the text manually.")
        except Exception as e:
            st.error(f"Could not read file: {e}. Please paste text manually.")

    # Pre-fill textarea with extracted text if available; otherwise keep what user typed
    current_val = extracted if extracted else st.session_state.get(fallback_key, "")
    text = st.text_area(
        f"✏️ Review / edit {label.lower()} (or paste directly):",
        value=current_val,
        height=height,
        key=fallback_key,
        placeholder=placeholder,
    )
    return text


# ─── Template attachment helper ───────────────────────────────────────────────
# Built-in named templates per module
_BUILTIN_TEMPLATES = {
    "course_profile": {
        "GIM Course Profile (Standard)": """\
SECTION 1 – COURSE OVERVIEW
Course Title:
Programme:
Credits:
Prerequisites:

SECTION 2 – COURSE DESCRIPTION
[3–5 sentence description]

SECTION 3 – COURSE OBJECTIVES
1.
2.
3.

SECTION 4 – COURSE LEARNING OUTCOMES (CLOs)
CLO1:
CLO2:
CLO3:

SECTION 5 – CLO–PLO MAPPING TABLE
[CLO vs PLO matrix]

SECTION 6 – SESSION-WISE PLAN
Session | Topic | Pedagogy | Activity | CLO

SECTION 7 – ASSESSMENT STRUCTURE
Component | Weightage | Week | CLO
Quizzes   |    15%    |  —   |
Mid-term  |    25%    |  8   |
End-term  |    40%    |  16  |
Project   |    20%    |  16  |

SECTION 8 – READING LIST
Textbooks:
Articles:

SECTION 9 – AI & ACADEMIC INTEGRITY POLICY
[Institutional statement]""",

        "PGDM Standard Course Profile": """\
Course Code:
Course Title:
Credits (L-T-P):
Term:
Programme: PGDM / PGDM-BDA / PGDM-HCM

LEARNING OUTCOMES:
After completing this course, students will be able to:
CLO1 [Remember/Understand]: ...
CLO2 [Apply]: ...
CLO3 [Analyse]: ...
CLO4 [Evaluate]: ...
CLO5 [Create]: ...

CLO–PLO ALIGNMENT:
       PLO1  PLO2  PLO3  PLO4  PLO5
CLO1    ✓
CLO2          ✓
CLO3                ✓
CLO4                      ✓
CLO5                            ✓

TEACHING PLAN: [16 sessions]
SESSION | TOPIC | PEDAGOGY | ACTIVITY | CLO

EVALUATION:
Continuous Assessment: 60%
  - Quizzes (3 × 5%) = 15%
  - Group Project = 25%
  - Class Participation = 20%
End-term Examination: 40%""",

        "Blank Template": """\
Course Title:
Programme:
Credits:
Sessions:
Target Students:

Objectives:

CLOs:

Assessment:

Reading List:""",
    },

    "handbook": {
        "Standard Handbook Template": """\
TITLE PAGE
Title:
Subtitle:
Author:
Edition:

PREFACE
Purpose:
Scope:
How to use this handbook:

CHAPTER STRUCTURE (repeat per chapter):
Chapter [N]: [Title]
Learning Objectives:
1.
2.
Beginner Explanation:
Intermediate Explanation:
Advanced Explanation:
Worked Example:
Practice Exercise:
Chapter Summary:

GLOSSARY
Term | Definition

MASTERY ROADMAP
Stage 1 – Awareness:
Stage 2 – Comprehension:
Stage 3 – Application:
Stage 4 – Mastery:""",

        "Research Handbook Template": """\
HANDBOOK: [Title]
Target: PhD Scholars / Research Students

MODULE 1: Introduction to [Topic]
MODULE 2: Literature Review Methodology
MODULE 3: Research Design
MODULE 4: Data Collection & Analysis
MODULE 5: Writing & Publication
MODULE 6: Ethics & Academic Integrity

Each module:
- Concept explanation
- Step-by-step guide
- Common pitfalls
- Checklist
- Resources""",
    },

    "teaching_content": {
        "Standard Session Plan Template": """\
SESSION PLAN
Topic:
Course:
Duration:
Date:

LEARNING OBJECTIVES:
By end of session, students will:
1.
2.
3.

INSTRUCTOR TIMELINE:
0–10 min  : Ice-breaker / Review
10–30 min : Core concept delivery
30–50 min : Activity / Case discussion
50–60 min : Summary + Exit ticket

SLIDE OUTLINE:
Slide 1: Title
Slide 2: Agenda
Slide 3–6: Core concept
Slide 7–8: Example
Slide 9: Activity
Slide 10: Summary

DISCUSSION QUESTIONS:
1.
2.
3.

EXIT TICKET: [Reflection prompt]""",

        "Flipped Classroom Template": """\
PRE-CLASS (student prep):
- Reading:
- Video:
- Pre-class quiz:

IN-CLASS:
0–15 min  : Q&A on pre-class material
15–35 min : Group problem-solving
35–55 min : Presentation / peer teaching
55–60 min : Wrap-up + next session preview

POST-CLASS:
- Assignment:
- Reflection journal:""",
    },

    "quiz_case": {
        "MCQ Question Bank Template": """\
QUESTION BANK
Topic:
Course:
Bloom's Level:

Q1. [Stem — clear, unambiguous]
A. [Distractor]
B. [Correct answer]
C. [Distractor]
D. [Distractor]
Answer: B
Explanation: [Why B is correct]
Bloom's Level: Apply
Difficulty: Medium

[Repeat for each question]

CASE STUDY TEMPLATE:
Title:
Background (100–150 words):
Data/Context:
Questions:
1. [Analysis question]
2. [Evaluation question]
3. [Synthesis question]
Solution Notes:""",

        "Rubric Template": """\
ASSESSMENT RUBRIC
Component:
Total Marks:

CRITERIA | Excellent (4) | Good (3) | Satisfactory (2) | Needs Work (1)
Content accuracy |  |  |  |
Depth of analysis |  |  |  |
Use of evidence |  |  |  |
Clarity of expression |  |  |  |
Critical thinking |  |  |  |""",
    },

    "research_productivity": {
        "Research Proposal Template": """\
RESEARCH PROPOSAL
Title:
Researcher:
Institution:
Date:

1. INTRODUCTION & BACKGROUND

2. PROBLEM STATEMENT

3. RESEARCH GAP

4. RESEARCH QUESTIONS
   RQ1:
   RQ2:
   RQ3:

5. OBJECTIVES

6. CONCEPTUAL FRAMEWORK

7. METHODOLOGY
   Design:
   Sample:
   Data Collection:
   Analysis:

8. EXPECTED CONTRIBUTIONS

9. TIMELINE
   Month 1–3:
   Month 4–6:
   Month 7–9:
   Month 10–12:

10. REFERENCES
    [CITATION NEEDED]""",

        "Journal Submission Checklist": """\
PRE-SUBMISSION CHECKLIST
Target Journal:
Impact Factor:
Submission Deadline:

□ Abstract within word limit
□ Keywords (5–8) provided
□ All figures ≥ 300 DPI
□ References in journal style
□ Ethics statement included
□ Data availability statement
□ Conflict of interest declared
□ Cover letter drafted
□ Supplementary material prepared
□ Author contributions stated""",
    },

    "job_application": {
        "Academic Application Checklist": """\
ACADEMIC JOB APPLICATION CHECKLIST
Institution:
Role:
Deadline:

DOCUMENTS REQUIRED:
□ Cover Letter (tailored)
□ CV / Resume (ATS-optimised)
□ Research Statement (2–3 pages)
□ Teaching Statement (1–2 pages)
□ Publication List
□ 3 Reference Letters
□ Writing Sample
□ Diversity Statement (if required)
□ Selection Criteria Responses

COVER LETTER STRUCTURE:
Para 1: Opening + role identification
Para 2: Research fit + key achievement
Para 3: Teaching fit + philosophy
Para 4: Service + institutional fit
Para 5: Closing + CTA""",

        "Research Statement Template": """\
RESEARCH STATEMENT
Name:
Institution:
Date:

CURRENT RESEARCH PROGRAMME
[2–3 sentences on your main research area]

KEY CONTRIBUTIONS
1. [Publication / project + impact]
2. [Publication / project + impact]

FUTURE RESEARCH AGENDA (3–5 years)
[What you plan to work on and why]

FUNDING PLANS
[Grants / fellowships you intend to apply for]

STUDENT MENTORING
[How you plan to involve students/PhDs]""",
    },

    "research_paper": {
        "Systematic Review Protocol": """\
SYSTEMATIC REVIEW PROTOCOL
Title:
Researchers:
Date:

PICO FRAMEWORK:
Population:
Intervention:
Comparison:
Outcome:

SEARCH STRATEGY:
Databases: [Web of Science, Scopus, PubMed, ...]
Keywords: [Primary] AND [Secondary]
Date range:
Language: English only / All

INCLUSION CRITERIA:
1.
2.
3.

EXCLUSION CRITERIA:
1.
2.

QUALITY ASSESSMENT TOOL: [CASP / PRISMA / ...]

DATA EXTRACTION FIELDS:
Author | Year | Study design | Sample | Key finding | Limitations""",

        "IEEE / APA Paper Outline": """\
PAPER OUTLINE

TITLE:

ABSTRACT (250 words):
Background | Gap | Objective | Method | Results | Implications

1. INTRODUCTION
   1.1 Background
   1.2 Motivation
   1.3 Research Gap
   1.4 Contributions
   1.5 Paper Organisation

2. RELATED WORK / LITERATURE REVIEW

3. METHODOLOGY
   3.1 Research Design
   3.2 Dataset
   3.3 Proposed Method / Model
   3.4 Evaluation Metrics

4. RESULTS & DISCUSSION
   4.1 Experimental Setup
   4.2 Quantitative Results
   4.3 Qualitative Analysis
   4.4 Ablation Study

5. CONCLUSION
   5.1 Summary
   5.2 Limitations
   5.3 Future Work

REFERENCES""",
    },
}


def template_upload_section(
    module_key: str,
    key_prefix: str,
    label: str = "Template",
    help_text: str = "Attach or select a template so the AI matches its exact structure and format.",
) -> str:
    """
    Render a collapsible template attachment section with:
    - Built-in named templates (dropdown)
    - File upload (PDF / DOCX / TXT)
    - Editable preview

    Returns the final template text (empty string if none provided).
    """
    templates = _BUILTIN_TEMPLATES.get(module_key, {})
    text_key  = f"{key_prefix}_template_text"

    with st.expander(f"📐 Attach or Select a {label} Template (optional)", expanded=False):
        st.markdown(
            f"""<div style="background:#F0F7FF;border-left:4px solid #2196F3;
            border-radius:6px;padding:10px 14px;margin-bottom:12px;font-size:0.85rem;
            color:#1A3A5C;">
            <b>ℹ️ Why attach a template?</b><br>
            {help_text} The generated prompt will instruct the AI to follow
            your template's structure, headings, and format exactly.
            </div>""",
            unsafe_allow_html=True,
        )

        # Source selector
        source = st.radio(
            "Template source:",
            ["None", "Built-in template", "Upload file", "Paste manually"],
            horizontal=True,
            key=f"{key_prefix}_tpl_source",
        )

        extracted = ""

        if source == "Built-in template" and templates:
            chosen = st.selectbox(
                "Select a built-in template:",
                list(templates.keys()),
                key=f"{key_prefix}_tpl_builtin",
            )
            extracted = templates[chosen]
            st.success(f"✅ Loaded: **{chosen}**")

        elif source == "Upload file":
            uploaded = st.file_uploader(
                "Upload template (PDF / DOCX / TXT)",
                type=["pdf", "docx", "txt"],
                key=f"{key_prefix}_tpl_file",
            )
            if uploaded:
                try:
                    extracted = extract_text_from_upload(uploaded)
                    if extracted:
                        st.success(f"✅ Extracted {len(extracted.split()):,} words from `{uploaded.name}`")
                    else:
                        st.warning("The file was readable but no text could be extracted. Paste the template manually below.")
                except Exception as e:
                    st.error(f"Could not read template: {e}")

        elif source == "Paste manually":
            extracted = ""  # let the text_area below capture it

        # Editable preview (always shown unless "None")
        if source != "None":
            current = extracted if extracted else st.session_state.get(text_key, "")
            template_text = st.text_area(
                "📋 Template content (editable):",
                value=current,
                height=220,
                key=text_key,
                placeholder="Your template structure will appear here. Edit as needed...",
            )
            # Show character count
            if template_text.strip():
                st.caption(f"{len(template_text.split()):,} words · {len(template_text):,} characters")
            return template_text
        else:
            # Clear stored template when "None" is selected
            if text_key in st.session_state:
                st.session_state[text_key] = ""
            return ""


def format_template_instruction(template_text: str, label: str = "output") -> str:
    """
    Convert template text into a prompt instruction block.
    Returns empty string if no template provided.
    """
    if not template_text or not template_text.strip():
        return ""
    return f"""
TEMPLATE TO FOLLOW:
The {label} must strictly follow the structure, headings, and format of the template below.
Do not add or remove major sections. Preserve all field labels and table structures.
Fill in every field with appropriate, substantive content.

--- TEMPLATE START ---
{template_text.strip()}
--- TEMPLATE END ---
"""


def apply_css():
    """Inject global CSS styling."""
    st.markdown(
        """
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600;700&family=Source+Sans+3:wght@300;400;600&display=swap');

        html, body, [class*="css"] {
            font-family: 'Source Sans 3', sans-serif;
        }

        /* ── Saffron-cream palette ── */
        :root {
            --saffron:      #E8651A;
            --saffron-dark: #C4500F;
            --gold:         #D4A017;
            --cream:        #FDF6EC;
            --charcoal:     #2C2C2C;
            --slate:        #4A4A5A;
            --success:      #2E7D52;
            --card-bg:      #FFFFFF;
            --border:       #EDE0D0;
            /* sidebar */
            --sb-bg:        #1E1206;
            --sb-text:      #F5E6D3;
            --sb-accent:    #F5A623;
            --sb-muted:     #C8A882;
        }

        /* ── Main background ── */
        .stApp {
            background: linear-gradient(160deg, #FDF6EC 0%, #FFF9F2 100%);
        }

        /* ════════════════════════════════════════
           SIDEBAR — full text visibility fix
        ════════════════════════════════════════ */
        [data-testid="stSidebar"] {
            background: var(--sb-bg) !important;
            border-right: 1px solid #3A2510;
        }

        /* All text nodes inside sidebar */
        [data-testid="stSidebar"] * {
            color: var(--sb-text) !important;
        }

        /* Radio option labels */
        [data-testid="stSidebar"] .stRadio label p,
        [data-testid="stSidebar"] .stRadio label span,
        [data-testid="stSidebar"] .stRadio div[role="radiogroup"] label {
            color: var(--sb-text) !important;
            font-size: 0.93rem !important;
        }

        /* Selected radio item — highlighted */
        [data-testid="stSidebar"] .stRadio div[role="radiogroup"] label:has(input:checked) {
            background: rgba(245,166,35,0.18) !important;
            border-radius: 6px;
            padding: 2px 6px;
        }

        /* Selectbox displayed value */
        [data-testid="stSidebar"] .stSelectbox [data-baseweb="select"] div,
        [data-testid="stSidebar"] .stSelectbox span,
        [data-testid="stSidebar"] .stSelectbox p {
            color: var(--sb-text) !important;
        }

        /* Selectbox dropdown box border */
        [data-testid="stSidebar"] .stSelectbox [data-baseweb="select"] {
            border-color: #5A3A1A !important;
            background-color: #2C1A08 !important;
        }

        /* Text inputs inside sidebar */
        [data-testid="stSidebar"] input[type="text"],
        [data-testid="stSidebar"] input {
            background-color: #2C1A08 !important;
            color: var(--sb-text) !important;
            border-color: #5A3A1A !important;
        }

        /* Sidebar labels (selectbox, text_input labels) */
        [data-testid="stSidebar"] label,
        [data-testid="stSidebar"] .stMarkdown p,
        [data-testid="stSidebar"] .stMarkdown strong,
        [data-testid="stSidebar"] .stMarkdown span {
            color: var(--sb-text) !important;
        }

        /* Sidebar markdown separators */
        [data-testid="stSidebar"] hr {
            border-color: #4A2D10 !important;
        }

        /* Sidebar header branding text */
        [data-testid="stSidebar"] .sidebar-brand {
            color: var(--sb-text) !important;
        }

        /* ════════════════════════════════════════
           MAIN CONTENT — labels & inputs
        ════════════════════════════════════════ */

        /* All form labels in main area */
        .stTextInput label,
        .stTextArea label,
        .stSelectbox label,
        .stMultiSelect label,
        .stNumberInput label,
        .stSlider label,
        .stCheckbox label,
        .stRadio label {
            color: var(--charcoal) !important;
            font-weight: 600 !important;
            font-size: 0.93rem !important;
        }

        /* Checkbox text */
        .stCheckbox label p,
        .stCheckbox label span {
            color: var(--charcoal) !important;
        }

        /* Input & textarea backgrounds */
        .stTextInput input,
        .stNumberInput input {
            background: #FFFFFF !important;
            color: var(--charcoal) !important;
            border: 1.5px solid #D4C4B0 !important;
            border-radius: 6px !important;
        }
        .stTextInput input:focus,
        .stNumberInput input:focus {
            border-color: var(--saffron) !important;
            box-shadow: 0 0 0 2px rgba(232,101,26,0.15) !important;
        }

        textarea {
            font-family: 'Courier New', monospace !important;
            font-size: 0.88rem !important;
            background: #FAFAFA !important;
            color: var(--charcoal) !important;
            border: 1.5px solid #D4C4B0 !important;
        }

        /* Selectbox */
        .stSelectbox [data-baseweb="select"] {
            border-color: #D4C4B0 !important;
        }

        /* ════════════════════════════════════════
           BUTTONS — primary & download
        ════════════════════════════════════════ */
        .stButton > button {
            background: linear-gradient(135deg, #E8651A, #C4500F) !important;
            color: #FFFFFF !important;
            border: none !important;
            border-radius: 8px !important;
            font-weight: 600 !important;
            font-size: 0.92rem !important;
            padding: 8px 20px !important;
            transition: all 0.2s ease !important;
            box-shadow: 0 2px 6px rgba(196,80,15,0.25) !important;
        }
        .stButton > button:hover {
            transform: translateY(-2px) !important;
            box-shadow: 0 6px 16px rgba(232,101,26,0.4) !important;
        }
        .stButton > button:active {
            transform: translateY(0) !important;
        }

        /* Download buttons — softer amber outline style */
        .stDownloadButton > button {
            background: #FFFFFF !important;
            color: #C4500F !important;
            border: 2px solid #E8651A !important;
            border-radius: 8px !important;
            font-weight: 600 !important;
            font-size: 0.88rem !important;
            transition: all 0.2s ease !important;
        }
        .stDownloadButton > button:hover {
            background: #FFF3E8 !important;
            border-color: #C4500F !important;
            box-shadow: 0 4px 10px rgba(232,101,26,0.2) !important;
        }

        /* Nav card buttons on home page */
        .nav-btn > button {
            background: #FFFFFF !important;
            color: #C4500F !important;
            border: 2px solid #E8651A !important;
            border-radius: 10px !important;
            font-weight: 600 !important;
            font-size: 0.85rem !important;
            padding: 6px 12px !important;
            width: 100% !important;
            transition: all 0.2s ease !important;
        }
        .nav-btn > button:hover {
            background: linear-gradient(135deg, #E8651A, #C4500F) !important;
            color: #FFFFFF !important;
            transform: translateY(-1px) !important;
        }

        /* ════════════════════════════════════════
           PAGE TYPOGRAPHY
        ════════════════════════════════════════ */
        .page-title {
            font-family: 'Playfair Display', serif;
            font-size: 2.1rem;
            font-weight: 700;
            color: var(--saffron-dark);
            margin-bottom: 4px;
        }
        .page-subtitle {
            font-size: 1rem;
            color: var(--slate);
            margin-bottom: 20px;
        }

        /* ── Section header ── */
        .section-header {
            display: flex;
            align-items: center;
            gap: 10px;
            margin: 24px 0 12px;
            padding-bottom: 8px;
            border-bottom: 2px solid var(--saffron);
        }
        .section-icon  { font-size: 1.3rem; }
        .section-title {
            font-family: 'Playfair Display', serif;
            font-size: 1.2rem;
            color: var(--saffron-dark);
            font-weight: 600;
        }

        /* ── Cards ── */
        .studio-card {
            background: var(--card-bg);
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 18px 20px;
            margin-bottom: 14px;
            box-shadow: 0 2px 10px rgba(232,101,26,0.07);
            color: var(--charcoal);
        }
        .studio-card * { color: inherit; }

        /* ── Tabs ── */
        .stTabs [data-baseweb="tab"] {
            font-weight: 600;
            color: var(--slate) !important;
            font-size: 0.95rem;
        }
        .stTabs [aria-selected="true"] {
            color: var(--saffron) !important;
            border-bottom-color: var(--saffron) !important;
        }

        /* ── Studio module tab selector: one clean row, no duplicate labels ── */
        div[role="radiogroup"][aria-label^="studio tab navigation"] {
            display: flex !important;
            gap: 0.75rem !important;
            width: 100% !important;
            margin: 0.2rem 0 1rem !important;
        }
        div[role="radiogroup"][aria-label^="studio tab navigation"] label {
            flex: 1 1 0 !important;
            justify-content: center !important;
            align-items: center !important;
            min-height: 42px !important;
            padding: 0.55rem 0.75rem !important;
            border: 1.5px solid #D4C4B0 !important;
            border-radius: 10px !important;
            background: #FFFFFF !important;
            box-shadow: 0 1px 4px rgba(196,80,15,0.08) !important;
            cursor: pointer !important;
            transition: all 0.18s ease-in-out !important;
        }
        div[role="radiogroup"][aria-label^="studio tab navigation"] label:hover {
            border-color: var(--saffron) !important;
            background: #FFF3E8 !important;
            transform: translateY(-1px) !important;
        }
        div[role="radiogroup"][aria-label^="studio tab navigation"] label:has(input:checked) {
            background: linear-gradient(135deg, #E8651A, #C4500F) !important;
            border-color: #C4500F !important;
            box-shadow: 0 4px 12px rgba(196,80,15,0.28) !important;
        }
        div[role="radiogroup"][aria-label^="studio tab navigation"] label:has(input:checked) p,
        div[role="radiogroup"][aria-label^="studio tab navigation"] label:has(input:checked) span {
            color: #FFFFFF !important;
            font-weight: 750 !important;
        }
        div[role="radiogroup"][aria-label^="studio tab navigation"] label p,
        div[role="radiogroup"][aria-label^="studio tab navigation"] label span {
            color: var(--slate) !important;
            font-size: 0.96rem !important;
            font-weight: 650 !important;
            white-space: normal !important;
            overflow-wrap: anywhere !important;
        }
        div[role="radiogroup"][aria-label^="studio tab navigation"] input[type="radio"] {
            display: none !important;
        }
        @media (max-width: 760px) {
            div[role="radiogroup"][aria-label^="studio tab navigation"] {
                flex-direction: column !important;
                gap: 0.45rem !important;
            }
        }

        /* ── Info/warning/success boxes ── */
        .stAlert p { color: var(--charcoal) !important; }

        /* ── Expander headers ── */
        .streamlit-expanderHeader {
            color: var(--charcoal) !important;
            font-weight: 600 !important;
        }

        /* ── Footer ── */
        .footer-note {
            text-align: center;
            color: var(--slate);
            font-size: 0.8rem;
            margin-top: 40px;
            padding: 12px;
            border-top: 1px solid var(--border);
        }

        /* ── Tag pills ── */
        .tag-pill {
            display: inline-block;
            background: #FFE8D6;
            color: #8B3A0A;
            border-radius: 20px;
            padding: 2px 10px;
            font-size: 0.78rem;
            margin: 2px;
            font-weight: 600;
        }

        /* ── Metric cards ── */
        .metric-card {
            background: linear-gradient(135deg, #FFF3E8, #FDECD6);
            border: 1px solid #EDE0D0;
            border-radius: 10px;
            padding: 16px;
            text-align: center;
        }
        .metric-value {
            font-family: 'Playfair Display', serif;
            font-size: 2rem;
            color: var(--saffron-dark);
            font-weight: 700;
        }
        .metric-label {
            font-size: 0.82rem;
            color: var(--slate);
            margin-top: 2px;
        }

        /* ── Multiselect tags ── */
        .stMultiSelect [data-baseweb="tag"] {
            background-color: #FFE8D6 !important;
            color: #8B3A0A !important;
        }
        .stMultiSelect [data-baseweb="tag"] span {
            color: #8B3A0A !important;
        }


        /* ── Production polish: readable, responsive, projection-friendly ── */
        .block-container {
            padding-top: 1.4rem !important;
            padding-bottom: 2.2rem !important;
            max-width: 1320px;
        }
        div[data-testid="stWidgetLabel"] p {
            color: var(--charcoal) !important;
            font-weight: 650 !important;
        }
        .stButton > button, .stDownloadButton > button {
            white-space: normal !important;
            min-height: 42px !important;
            line-height: 1.25 !important;
        }
        .stTextArea textarea {
            white-space: pre-wrap !important;
            overflow-wrap: anywhere !important;
        }
        .stFileUploader section {
            border: 1.5px dashed #D4A017 !important;
            background: #FFF9F2 !important;
            border-radius: 12px !important;
        }
        div[data-testid="stExpander"] {
            border-color: var(--border) !important;
            border-radius: 10px !important;
            background: #FFFFFFCC !important;
        }
        div[data-testid="stMetric"] {
            background: #FFFFFF;
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 12px;
        }
        @media (max-width: 900px) {
            .page-title { font-size: 1.65rem !important; }
            .page-subtitle { font-size: 0.92rem !important; }
            .section-title { font-size: 1.05rem !important; }
            .studio-card { padding: 14px 15px !important; }
            [data-testid="stSidebar"] .stRadio label p { font-size: 0.86rem !important; }
        }
        </style>
        """,
        unsafe_allow_html=True,
    )
